import React from 'react';

const AboutPage: React.FC = () => {
  return (
    <div className="min-h-screen p-8">
      <header className="mb-8 text-center">
        <h1 className="type-1 text-cardinal-red font-semibold mb-4">
          Views and Visits
        </h1>
      </header>

      <div className="max-w-4xl mx-auto">
        <section className="mb-25 text-center">
          <p className="text-lg text-black mb-15 leading-relaxed">
            <a
              href="https://docs.acquia.com/acquia-cloud-platform/acquia-views-and-visits-usage-limits-and-overages?v=2"
              className="text-digital-blue hocus:text-cardinal-red underline su-link--external"
              target="_blank"
              rel="noopener noreferrer"
            >
              See Acquia documentation for more information about Views and Visits
              <span className="sr-only"> (opens in a new tab)</span>
            </a>
          </p>
        </section>

        <section className="bg-black-10 rounded-lg p-20 border-2 border-black-10 mb-25">
          <h2 className="type-2 font-semibold mb-15 text-cardinal-red">
            Views
          </h2>
          <p className="text-lg text-black mb-15 leading-relaxed">
            <span className="font-semibold text-cardinal-red">Views</span> are any requests made to your Acquia-hosted Drupal application. Views exclude static content (image, CSS, JS, etc.), redirect requests, client errors, and activity originating from certain known bots and crawlers. This ensures that you do not pay for:
          </p>
          <ul className="ml-20 text-lg text-black mb-15">
            <li className="mb-5">Errors delivered to your site visitors</li>
            <li className="mb-5">Extra hop that some visitors take when they are redirected</li>
            <li className="mb-5">Noise generated by the most common bots that impact Acquia's customers</li>
          </ul>
          <p className="text-lg text-black leading-relaxed">
            Views count is not related to the Drupal Views module, or content returned by that module.
          </p>
        </section>

        <section className="bg-black-10 rounded-lg p-20 border-2 border-black-10 mb-25">
          <h2 className="type-2 font-semibold mb-15 text-cardinal-red">
            Visits
          </h2>
          <p className="text-lg text-black mb-15 leading-relaxed">
            A <span className="font-semibold text-cardinal-red">Visit</span> is one or more Views from the same user agent within the same hour. You can identify user agents based on IP, cookies, or headers as determined by the implementation.
          </p>
          <p className="text-lg text-black leading-relaxed">
            <span className="font-semibold">Example:</span> A user navigates to a website at 10:15 AM, browsing to the homepage and the About Us page within five minutes. Assuming only a single request that meets the definition of a View is triggered when the user navigates to each page, this counts as two Views and one Visit.
          </p>
        </section>

      </div>
    </div>
  );
};

export default AboutPage;